### ISSUE TITLE
如何修改目录内章节字体

### ISSUE THREAD

**Issue by Cugtyt** [tsaoyu/WHUT#4]
![image](https://user-images.githubusercontent.com/16632454/40695735-111a4876-63f5-11e8-9f66-8ef71121a85a.png)

如何将章标题改为宋体，不加粗，和其他节标题一样，目录这两个字保持黑体？

**Comment by Cugtyt** [comment]
我使用{\songti\tableofcontents}修改为了宋体，但是数字依旧是加粗的，请问如何修改？

![image](https://user-images.githubusercontent.com/16632454/40697066-2fb6a04e-63fb-11e8-93de-838abccd0cca.png)

**Comment by tsaoyu** [comment]
To change fonts in ToC check this package [tocloft](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/tocloft/tocloft.pdf). 

 [Discussion](http://180.76.179.192/forum.php?mod=viewthread&tid=154865) here might also help.

**Comment by Cugtyt** [comment]
\usepackage[subfigure]{tocloft} 
\renewcommand{\cftsecleader}{\cftdotfill{\cftdotsep}} 
\renewcommand{\cftsecfont}{\songti}
\renewcommand{\cftsecpagefont}{\songti}

我使用这个命令字体可以了，但是这导致了目录第一页出现了页码，请问如何解决？谢谢

**Comment by tsaoyu** [comment]
Could you try `\thispagestyle{empty}`?

**Comment by Cugtyt** [comment]
ok, I solve it, here is the summary:
```
\usepackage[subfigure]{tocloft} %tocloft packages
\renewcommand{\cftsecleader}{\cftdotfill{\cftdotsep}} % add dot of chepters if needed
\renewcommand{\cftsecfont}{\songti} % set section font
\renewcommand{\cftsecpagefont}{\songti} % set page number font
```
But page number of the first  table of contents page occurs, use
```
 \tocloftpagestyle{empty}
```
